name: weak_map
description: WeakMap is a map of key/value pairs in which the keys are weakly referenced. WeakContainer is a weak-reference that only lets you check if some object it the same you had before.
version: 1.0.5
author: Marcelo Glasberg <marcglasberg@gmail.com>
homepage: https://github.com/marcglasberg/weak_map

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  meta: 1.1.8

dev_dependencies:
  test: 1.14.3



