name: weak_map
description: WeakMap is a map where the keys are weakly referenced. WeakContainer lets you check if an object is the same you had before. Cache functions for memoization with weak-references.
version: 2.0.4
homepage: https://github.com/marcglasberg/weak_map
# author: Marcelo Glasberg <marcglasberg@gmail.com>

environment:
  sdk: '>=2.13.0 <3.0.0'

dev_dependencies:
  test: ^1.17.12



