name: weak_map
description: WeakMap is a map whose keys are weakly held, to attach data to objects without keeping them alive. Cache functions for memoization over immutable state.
version: 4.1.0
# author: Marcelo Glasberg <marcglasberg@gmail.com>
homepage: https://github.com/marcglasberg/weak_map
topics:
  - memory
  - memory-management
  - cache
  - collections
  - data-structures

environment:
  sdk: '>=3.0.0 <4.0.0'

dev_dependencies:
  test: ^1.17.12
