name: weak_map
description: WeakMap is a map where the keys are weakly referenced. WeakContainer lets you check if an object is the same you had before. Cache functions for memoization with weak-references.
version: 4.0.1
# author: Marcelo Glasberg <marcglasberg@gmail.com>
homepage: https://github.com/marcglasberg/weak_map
topics:
  - memory
  - memory-management
  - cache
  - collections
  - data-structures

environment:
  sdk: '>=2.19.0 <4.0.0'

dev_dependencies:
  test: ^1.17.12
